### ISSUE TITLE
Web head not usable when device is rotated.

### ISSUE THREAD

**Issue by arunkumar9t2** [arunkumar9t2/chromer#1]
Currently if device is rotated after web head service is created, it is not possible to close the web heads and they stay in the middle of the screen.

**Comment by denilsonsa** [comment]
I came here to report this exact same issue. How to reproduce:

1. Enable web-heads, configured to be shown at the right.
2. Open Barcode Scanner (which forces landscape mode).
3. Scan a link, open in Chromer.
4. There will be a web-head at the right of the screen, in landscape mode.
5. Exit Barcode Scanner. Now the device is in portrait mode.
6. BUG! Chromer still positions web-heads and the trash can as if it were in landscape mode, so the web-heads from the right are now off-screen.

Of course, there are several ways to reproduce this bug, I just wanted to document here one of the ways.

**Comment by arunkumar9t2** [comment]
Thanks. I am aware and will address this issue on priority for next release.

**Comment by arunkumar9t2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rotation issue](https://trello.com/c/Orffdrif/39-rotation-issue)

**Comment by arunkumar9t2** [comment]
Fixed for 1.7.
