### ISSUE TITLE
Differentiate between adding a Chrome shortcut to the home screen and a Chromer shortcut

### ISSUE THREAD

**Issue by pkoepke** [arunkumar9t2/chromer#25]
Enhancement request: There are 2 options called "Add to Home Screen" - one in the context menu and one accessible from "More." The first adds a link that opens in Chrome and the latter opens in Chrome. Please rename these to clarify which is a browser shortcut and which launches Chromer.

**Comment by arunkumar9t2** [comment]
I understand the confusion. Google Chrome now provides inbuilt 'Add to homescreen' option since recent builds and as of now there is no API to disable that menu option. I could probably add another 'Add to homescreen (Chromer)' but it'll only cause more confusion. I'll think about a better way.

**Comment by pkoepke** [comment]
I think "Add Chromer shortcut to home screen" would be clear.

**Comment by arunkumar9t2** [comment]
Hi, I changed text **More** to **Chromer Options** in the overflow menu. Tapping this will launch Chromer's options where you can add shortcuts from Chromer. Will be available in 1.7.3.

**Comment by pkoepke** [comment]
Great, thanks!
