### ISSUE TITLE
Allow custom names for Chromer shortcuts and implement new Oreo API

### ISSUE THREAD

**Issue by pkoepke** [arunkumar9t2/chromer#26]
When you open a web page then go to Context Menu > More > Add to Home Screen, the Chromer shortcut gets the title of the page for its name. This is annoying on websites that do not have descriptive titles on every page. Please add a pop-up to give the shortcut a custom name if desired.

**Comment by arunkumar9t2** [comment]
Agreed, will work on it. Thanks!
