### ISSUE TITLE
editing a source code

### ISSUE THREAD

**Issue by lmdevs** [arunkumar9t2/chromer#29]
Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :RxSuggestions:library.

**Comment by arunkumar9t2** [comment]
My mistake. I should have made contributing instructions clearer. I use submodules, so after checking the repo out, please do

```
git submodule init 
git submodule update
```

This should fetch RxSuggestions and ArticleView repos.

**Comment by arunkumar9t2** [comment]
Closing the issue now, please feel free to open it again if you face any issues.
