### ISSUE TITLE
Focus back button bug

### ISSUE THREAD

**Issue by FISHunderscore** [arunkumar9t2/chromer#30]
Pressing the back button does not properly close a Focus custom tab (using slide over mode). It leaves the "erase browsing history" notification active, whereas it should instead perform the same action that pressing the "x" in the upper left does (thereby removing this notification).

Thank you, and keep up the great work!

**Comment by arunkumar9t2** [comment]
Hi, this was an issue with Focus browser and not Chromer. Looks like the Focus team have already fixed this. Please let me know if it is clearing the notification.
