### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by mohitmanuja** [arunkumar9t2/chromer#31]
@arunkumar9t2 
I am getting this error while running this project: 

Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :RxSuggestions:library.

**Comment by arunkumar9t2** [comment]
Could you try doing a clean build? I am working on publishing RxSuggestions as as separate library. Then I can add that as gradle dependency instead of adding as a submodule.

**Comment by mohitmanuja** [comment]
@arunkumar9t2 Yes, I tried but it is not working.

**Comment by arunkumar9t2** [comment]
I fixed the repo and now rxsuggestions is added as a gradle dependency. Please let me know if you face any issues. Closing the issue until then.
