### ISSUE TITLE
Encoding problem in search bar

### ISSUE THREAD

**Issue by mockroot** [arunkumar9t2/chromer#36]
Hi, i have a problem with Turkish characters in search area. They are not displaying correctly. (e.g. "ö" "ç")
Screenshot here:
![photo_2017-11-26_20-25-39](https://user-images.githubusercontent.com/24863704/33242565-1ec9b838-d2e8-11e7-8915-781ad97db374.jpg)

**Comment by arunkumar9t2** [comment]
Thanks for reporting. I tested this and can confirm the issue exists. I will fix it for future releases.

**Comment by mockroot** [comment]
Thank you.
